######################################################################
# Automatically generated by qmake (3.0) Wed Sep 10 12:19:56 2014
######################################################################

QT -= core gui
TEMPLATE = lib 
TARGET = mongo-cxx-driver

INCLUDEPATH += ./mongo-cxx-driver/src \
    ./mongo-cxx-driver/src/third_party \
    ./mongo-cxx-driver/src/mongo/client \
    ./mongo-cxx-driver/src/third_party/gtest-1.7.0 \
    ./mongo-cxx-driver/src/third_party/gtest-1.7.0/include \
    C:/local/boost_1_56_0 \


CONFIG += console

# MongoDB needs to be built with unicode support, see https://groups.google.com/forum/?fromgroups=#!topic/mongodb-user/0n3dosIy9XY
DEFINES += _UNICODE


# Input
HEADERS += mongo-cxx-driver/src/mongo/client/redef_macros.h \
           mongo-cxx-driver/src/mongo/pch.h \
           mongo-cxx-driver/src/mongo/base/disallow_copying.h \
           mongo-cxx-driver/src/mongo/base/global_initializer.h \
           mongo-cxx-driver/src/mongo/base/global_initializer_registerer.h \
           mongo-cxx-driver/src/mongo/base/init.h \
           mongo-cxx-driver/src/mongo/base/error_codes.h \
           mongo-cxx-driver/src/mongo/base/initializer.h \
           mongo-cxx-driver/src/mongo/base/initializer_context.h \
           mongo-cxx-driver/src/mongo/base/initializer_dependency_graph.h \
           mongo-cxx-driver/src/mongo/base/initializer_function.h \
           mongo-cxx-driver/src/mongo/base/initializer_functions.h \
           mongo-cxx-driver/src/mongo/base/make_string_vector.h \
           mongo-cxx-driver/src/mongo/base/owned_pointer_vector.h \
           mongo-cxx-driver/src/mongo/base/parse_number.h \
           mongo-cxx-driver/src/mongo/base/status-inl.h \
           mongo-cxx-driver/src/mongo/base/status.h \
           mongo-cxx-driver/src/mongo/base/status_with.h \
           mongo-cxx-driver/src/mongo/base/string_data-inl.h \
           mongo-cxx-driver/src/mongo/base/string_data.h \
           mongo-cxx-driver/src/mongo/bson/bson-inl.h \
           mongo-cxx-driver/src/mongo/bson/bson.h \
           mongo-cxx-driver/src/mongo/bson/bson_builder_base.h \
           mongo-cxx-driver/src/mongo/bson/bson_db.h \
           mongo-cxx-driver/src/mongo/bson/bson_field.h \
           mongo-cxx-driver/src/mongo/bson/bson_validate.h \
           mongo-cxx-driver/src/mongo/bson/bsonelement.h \
           mongo-cxx-driver/src/mongo/bson/bsonmisc.h \
           mongo-cxx-driver/src/mongo/bson/bsonobj.h \
           mongo-cxx-driver/src/mongo/bson/bsonobjbuilder.h \
           mongo-cxx-driver/src/mongo/bson/bsonobjiterator.h \
           mongo-cxx-driver/src/mongo/bson/bsontypes.h \
           mongo-cxx-driver/src/mongo/bson/inline_decls.h \
           mongo-cxx-driver/src/mongo/bson/oid.h \
           mongo-cxx-driver/src/mongo/bson/optime.h \
           mongo-cxx-driver/src/mongo/bson/ordering.h \
           mongo-cxx-driver/src/mongo/client/clientOnly-private.h \
           mongo-cxx-driver/src/mongo/client/connpool.h \
           mongo-cxx-driver/src/mongo/client/constants.h \
           mongo-cxx-driver/src/mongo/client/dbclient.h \
           mongo-cxx-driver/src/mongo/client/dbclient_rs.h \
           mongo-cxx-driver/src/mongo/client/dbclientcursor.h \
           mongo-cxx-driver/src/mongo/client/dbclientinterface.h \
           mongo-cxx-driver/src/mongo/client/dbclientmockcursor.h \
           mongo-cxx-driver/src/mongo/client/export_macros.h \
           mongo-cxx-driver/src/mongo/client/gridfs.h \
           mongo-cxx-driver/src/mongo/client/init.h \
           mongo-cxx-driver/src/mongo/client/replica_set_monitor.h \
           mongo-cxx-driver/src/mongo/client/replica_set_monitor_internal.h \
#           mongo-cxx-driver/src/mongo/client/sasl_client_authenticate.h \
#           mongo-cxx-driver/src/mongo/client/sasl_client_session.h \
           mongo-cxx-driver/src/mongo/client/syncclusterconnection.h \
           mongo-cxx-driver/src/mongo/client/undef_macros.h \
           mongo-cxx-driver/src/mongo/db/client_basic.h \
           mongo-cxx-driver/src/mongo/db/dbmessage.h \
           mongo-cxx-driver/src/mongo/db/jsobj.h \
           mongo-cxx-driver/src/mongo/db/json.h \
           mongo-cxx-driver/src/mongo/db/lasterror.h \
           mongo-cxx-driver/src/mongo/db/namespace_string-inl.h \
           mongo-cxx-driver/src/mongo/db/namespace_string.h \
           mongo-cxx-driver/src/mongo/db/server_options.h \
           mongo-cxx-driver/src/mongo/logger/appender.h \
           mongo-cxx-driver/src/mongo/logger/console.h \
           mongo-cxx-driver/src/mongo/logger/console_appender.h \
           mongo-cxx-driver/src/mongo/logger/encoder.h \
           mongo-cxx-driver/src/mongo/logger/labeled_level.h \
           mongo-cxx-driver/src/mongo/logger/log_domain-impl.h \
           mongo-cxx-driver/src/mongo/logger/log_domain.h \
           mongo-cxx-driver/src/mongo/logger/log_manager.h \
           mongo-cxx-driver/src/mongo/logger/log_severity-inl.h \
           mongo-cxx-driver/src/mongo/logger/log_severity.h \
           mongo-cxx-driver/src/mongo/logger/logger.h \
           mongo-cxx-driver/src/mongo/logger/logstream_builder.h \
           mongo-cxx-driver/src/mongo/logger/message_event.h \
           mongo-cxx-driver/src/mongo/logger/message_event_utf8_encoder.h \
           mongo-cxx-driver/src/mongo/logger/message_log_domain.h \
           mongo-cxx-driver/src/mongo/logger/ramlog.h \
           mongo-cxx-driver/src/mongo/logger/rotatable_file_appender.h \
           mongo-cxx-driver/src/mongo/logger/rotatable_file_manager.h \
           mongo-cxx-driver/src/mongo/logger/rotatable_file_writer.h \
           mongo-cxx-driver/src/mongo/logger/tee.h \
           mongo-cxx-driver/src/mongo/platform/atomic_intrinsics.h \
           mongo-cxx-driver/src/mongo/platform/atomic_intrinsics_gcc_generic.h \
           mongo-cxx-driver/src/mongo/platform/atomic_intrinsics_gcc_intel.h \
           mongo-cxx-driver/src/mongo/platform/atomic_intrinsics_win32.h \
           mongo-cxx-driver/src/mongo/platform/atomic_word.h \
           mongo-cxx-driver/src/mongo/platform/backtrace.h \
           mongo-cxx-driver/src/mongo/platform/basic.h \
           mongo-cxx-driver/src/mongo/platform/compiler.h \
           mongo-cxx-driver/src/mongo/platform/compiler_gcc.h \
           mongo-cxx-driver/src/mongo/platform/compiler_msvc.h \
           mongo-cxx-driver/src/mongo/platform/cstdint.h \
           mongo-cxx-driver/src/mongo/platform/float_utils.h \
           mongo-cxx-driver/src/mongo/platform/hash_namespace.h \
           mongo-cxx-driver/src/mongo/platform/process_id.h \
           mongo-cxx-driver/src/mongo/platform/random.h \
           mongo-cxx-driver/src/mongo/platform/strtoll.h \
           mongo-cxx-driver/src/mongo/platform/unordered_map.h \
           mongo-cxx-driver/src/mongo/platform/unordered_set.h \
           mongo-cxx-driver/src/mongo/platform/windows_basic.h \
           mongo-cxx-driver/src/mongo/s/bson_serializable.h \
           mongo-cxx-driver/src/mongo/s/chunk_version.h \
           mongo-cxx-driver/src/mongo/s/shard.h \
           mongo-cxx-driver/src/mongo/s/stale_exception.h \
           mongo-cxx-driver/src/mongo/unittest/unittest.h \
           mongo-cxx-driver/src/mongo/util/allocator.h \
           mongo-cxx-driver/src/mongo/util/assert_util.h \
           mongo-cxx-driver/src/mongo/util/background.h \
           mongo-cxx-driver/src/mongo/util/base64.h \
           mongo-cxx-driver/src/mongo/util/bufreader.h \
           mongo-cxx-driver/src/mongo/util/debug_util.h \
           mongo-cxx-driver/src/mongo/util/embedded_builder.h \
           mongo-cxx-driver/src/mongo/util/exit_code.h \
           mongo-cxx-driver/src/mongo/util/fail_point.h \
           mongo-cxx-driver/src/mongo/util/fail_point_registry.h \
           mongo-cxx-driver/src/mongo/util/fail_point_service.h \
           mongo-cxx-driver/src/mongo/util/goodies.h \
           mongo-cxx-driver/src/mongo/util/heapcheck.h \
           mongo-cxx-driver/src/mongo/util/hex.h \
           mongo-cxx-driver/src/mongo/util/log.h \
           mongo-cxx-driver/src/mongo/util/map_util.h \
           mongo-cxx-driver/src/mongo/util/md5.h \
           mongo-cxx-driver/src/mongo/util/md5.hpp \
           mongo-cxx-driver/src/mongo/util/password_digest.h \
           mongo-cxx-driver/src/mongo/util/scopeguard.h \
           mongo-cxx-driver/src/mongo/util/stacktrace.h \
           mongo-cxx-driver/src/mongo/util/startup_test.h \
           mongo-cxx-driver/src/mongo/util/string_map.h \
           mongo-cxx-driver/src/mongo/util/stringutils.h \
           mongo-cxx-driver/src/mongo/util/text.h \
           mongo-cxx-driver/src/mongo/util/time_support.h \
           mongo-cxx-driver/src/mongo/util/timer-generic-inl.h \
           mongo-cxx-driver/src/mongo/util/timer-inl.h \
           mongo-cxx-driver/src/mongo/util/timer-posixclock-inl.h \
           mongo-cxx-driver/src/mongo/util/timer-win32-inl.h \
           mongo-cxx-driver/src/mongo/util/timer.h \
           mongo-cxx-driver/src/mongo/util/unordered_fast_key_table.h \
           mongo-cxx-driver/src/mongo/util/unordered_fast_key_table_internal.h \
           mongo-cxx-driver/src/mongo/util/version.h \
           mongo-cxx-driver/src/third_party/murmurhash3/MurmurHash3.h \
           mongo-cxx-driver/src/third_party/tz/timegm_private.h \
           mongo-cxx-driver/src/third_party/tz/timegm_tzfile.h \
           mongo-cxx-driver/src/mongo/bson/util/atomic_int.h \
           mongo-cxx-driver/src/mongo/bson/util/bson_extract.h \
           mongo-cxx-driver/src/mongo/bson/util/builder.h \
           mongo-cxx-driver/src/mongo/bson/util/misc.h \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_conn_registry.h \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_dbclient_connection.h \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_dbclient_cursor.h \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_remote_db_server.h \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_replica_set.h \
           mongo-cxx-driver/src/mongo/util/concurrency/mutex.h \
           mongo-cxx-driver/src/mongo/util/concurrency/mutexdebugger.h \
           mongo-cxx-driver/src/mongo/util/concurrency/shared_mutex_win.hpp \
           mongo-cxx-driver/src/mongo/util/concurrency/spin_lock.h \
           mongo-cxx-driver/src/mongo/util/concurrency/synchronization.h \
           mongo-cxx-driver/src/mongo/util/concurrency/thread_name.h \
           mongo-cxx-driver/src/mongo/util/concurrency/threadlocal.h \
           mongo-cxx-driver/src/mongo/util/concurrency/ticketholder.h \
           mongo-cxx-driver/src/mongo/util/concurrency/value.h \
           mongo-cxx-driver/src/mongo/util/mongoutils/html.h \
           mongo-cxx-driver/src/mongo/util/mongoutils/str.h \
           mongo-cxx-driver/src/mongo/util/net/hostandport.h \
           mongo-cxx-driver/src/mongo/util/net/httpclient.h \
           mongo-cxx-driver/src/mongo/util/net/listen.h \
           mongo-cxx-driver/src/mongo/util/net/message.h \
           mongo-cxx-driver/src/mongo/util/net/message_port.h \
           mongo-cxx-driver/src/mongo/util/net/sock.h \
           mongo-cxx-driver/src/mongo/util/net/socket_poll.h \
           mongo-cxx-driver/src/mongo/util/net/ssl_manager.h \
           mongo-cxx-driver/src/mongo/util/net/ssl_options.h \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/prime_tables.h \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample1.h \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample2.h \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample3-inl.h \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample4.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-internal-inl.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-param-test_test.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-typed-test_test.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/production.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/fused-src/gtest/gtest.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest-death-test.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest-message.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest-param-test.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest-printers.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest-spi.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest-test-part.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest-typed-test.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest_pred_impl.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/gtest_prod.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-death-test-internal.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-filepath.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-internal.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-linked_ptr.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-param-util-generated.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-param-util.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-port.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-string.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-tuple.h \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/include/gtest/internal/gtest-type-util.h \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/xcode/Samples/FrameworkSample/widget.h

SOURCES += mongo-cxx-driver/src/mongo/clienttest_main.cpp \
           mongo-cxx-driver/src/mongo/pch.cpp \
           mongo-cxx-driver/src/third_party/shim_boost.cpp \
           mongo-cxx-driver/src/mongo/base/global_initializer.cpp \
           mongo-cxx-driver/src/mongo/base/global_initializer_registerer.cpp \
           mongo-cxx-driver/src/mongo/base/init.cpp \
           mongo-cxx-driver/src/mongo/base/error_codes.cpp \
           mongo-cxx-driver/src/mongo/base/initializer.cpp \
           mongo-cxx-driver/src/mongo/base/initializer_context.cpp \
           mongo-cxx-driver/src/mongo/base/initializer_dependency_graph.cpp \
           mongo-cxx-driver/src/mongo/base/make_string_vector.cpp \
           mongo-cxx-driver/src/mongo/base/parse_number.cpp \
           mongo-cxx-driver/src/mongo/base/parse_number_test.cpp \
           mongo-cxx-driver/src/mongo/base/status.cpp \
           mongo-cxx-driver/src/mongo/base/string_data.cpp \
           mongo-cxx-driver/src/mongo/bson/bson_field_test.cpp \
           mongo-cxx-driver/src/mongo/bson/bson_obj_test.cpp \
           mongo-cxx-driver/src/mongo/bson/bson_validate.cpp \
           mongo-cxx-driver/src/mongo/bson/bson_validate_test.cpp \
           mongo-cxx-driver/src/mongo/bson/bsonobjbuilder_test.cpp \
           mongo-cxx-driver/src/mongo/bson/oid.cpp \
           mongo-cxx-driver/src/mongo/bson/optime.cpp \
           mongo-cxx-driver/src/mongo/client/clientAndShell.cpp \
           mongo-cxx-driver/src/mongo/client/clientOnly.cpp \
           mongo-cxx-driver/src/mongo/client/connpool.cpp \
           mongo-cxx-driver/src/mongo/client/dbclient.cpp \
           mongo-cxx-driver/src/mongo/client/dbclient_rs.cpp \
           mongo-cxx-driver/src/mongo/client/dbclient_rs_test.cpp \
           mongo-cxx-driver/src/mongo/client/dbclientcursor.cpp \
           mongo-cxx-driver/src/mongo/client/gridfs.cpp \
           mongo-cxx-driver/src/mongo/client/include_bsonh_test.cpp \
           mongo-cxx-driver/src/mongo/client/include_dbclienth_test.cpp \
           mongo-cxx-driver/src/mongo/client/init.cpp \
           mongo-cxx-driver/src/mongo/client/replica_set_monitor.cpp \
           mongo-cxx-driver/src/mongo/client/replica_set_monitor_test.cpp \
#           mongo-cxx-driver/src/mongo/client/sasl_client_authenticate.cpp \
#           mongo-cxx-driver/src/mongo/client/sasl_client_authenticate_impl.cpp \
#           mongo-cxx-driver/src/mongo/client/sasl_client_session.cpp \
#           mongo-cxx-driver/src/mongo/client/sasl_sspi.cpp \
           mongo-cxx-driver/src/mongo/client/scoped_db_conn_test.cpp \
           mongo-cxx-driver/src/mongo/client/syncclusterconnection.cpp \
           mongo-cxx-driver/src/mongo/db/dbmessage.cpp \
           mongo-cxx-driver/src/mongo/db/dbmessage_test.cpp \
           mongo-cxx-driver/src/mongo/db/jsobj.cpp \
           mongo-cxx-driver/src/mongo/db/json.cpp \
           mongo-cxx-driver/src/mongo/db/lasterror.cpp \
           mongo-cxx-driver/src/mongo/db/server_options.cpp \
           mongo-cxx-driver/src/mongo/dbtests/jsobjtests.cpp \
           mongo-cxx-driver/src/mongo/dbtests/jsontests.cpp \
           mongo-cxx-driver/src/mongo/dbtests/mock_dbclient_conn_test.cpp \
           mongo-cxx-driver/src/mongo/dbtests/mock_replica_set_test.cpp \
           mongo-cxx-driver/src/mongo/dbtests/replica_set_monitor_test.cpp \
           mongo-cxx-driver/src/mongo/logger/console.cpp \
           mongo-cxx-driver/src/mongo/logger/console_test.cpp \
           mongo-cxx-driver/src/mongo/logger/log_manager.cpp \
           mongo-cxx-driver/src/mongo/logger/log_severity.cpp \
           mongo-cxx-driver/src/mongo/logger/log_test.cpp \
           mongo-cxx-driver/src/mongo/logger/logger.cpp \
           mongo-cxx-driver/src/mongo/logger/logstream_builder.cpp \
           mongo-cxx-driver/src/mongo/logger/message_event_utf8_encoder.cpp \
           mongo-cxx-driver/src/mongo/logger/message_log_domain.cpp \
           mongo-cxx-driver/src/mongo/logger/ramlog.cpp \
           mongo-cxx-driver/src/mongo/logger/rotatable_file_manager.cpp \
           mongo-cxx-driver/src/mongo/logger/rotatable_file_writer.cpp \
           mongo-cxx-driver/src/mongo/logger/rotatable_file_writer_test.cpp \
           mongo-cxx-driver/src/mongo/platform/atomic_word_test.cpp \
           mongo-cxx-driver/src/mongo/platform/backtrace.cpp \
           mongo-cxx-driver/src/mongo/platform/process_id.cpp \
           mongo-cxx-driver/src/mongo/platform/process_id_test.cpp \
           mongo-cxx-driver/src/mongo/platform/random.cpp \
           mongo-cxx-driver/src/mongo/platform/random_test.cpp \
           mongo-cxx-driver/src/mongo/util/assert_util.cpp \
           mongo-cxx-driver/src/mongo/util/background.cpp \
           mongo-cxx-driver/src/mongo/util/base64.cpp \
           mongo-cxx-driver/src/mongo/util/debug_util.cpp \
           mongo-cxx-driver/src/mongo/util/fail_point.cpp \
           mongo-cxx-driver/src/mongo/util/fail_point_registry.cpp \
           mongo-cxx-driver/src/mongo/util/fail_point_service.cpp \
           mongo-cxx-driver/src/mongo/util/hex.cpp \
           mongo-cxx-driver/src/mongo/util/log.cpp \
           mongo-cxx-driver/src/mongo/util/md5.cpp \
           mongo-cxx-driver/src/mongo/util/password_digest.cpp \
           mongo-cxx-driver/src/mongo/util/stacktrace.cpp \
           mongo-cxx-driver/src/mongo/util/stringutils.cpp \
           mongo-cxx-driver/src/mongo/util/stringutils_test.cpp \
           mongo-cxx-driver/src/mongo/util/text.cpp \
           mongo-cxx-driver/src/mongo/util/time_support.cpp \
           mongo-cxx-driver/src/mongo/util/time_support_test.cpp \
           mongo-cxx-driver/src/mongo/util/timer.cpp \
           mongo-cxx-driver/src/mongo/util/util.cpp \
           mongo-cxx-driver/src/mongo/util/version.cpp \
           mongo-cxx-driver/src/third_party/murmurhash3/MurmurHash3.cpp \
           mongo-cxx-driver/src/third_party/tz/timegm.c \
           mongo-cxx-driver/src/mongo/bson/bsondemo/bsondemo.cpp \
           mongo-cxx-driver/src/mongo/bson/util/bson_extract.cpp \
           mongo-cxx-driver/src/mongo/bson/util/bson_extract_test.cpp \
           mongo-cxx-driver/src/mongo/client/examples/arrayExample.cpp \
           mongo-cxx-driver/src/mongo/client/examples/authTest.cpp \
           mongo-cxx-driver/src/mongo/client/examples/clientTest.cpp \
           mongo-cxx-driver/src/mongo/client/examples/first.cpp \
           mongo-cxx-driver/src/mongo/client/examples/httpClientTest.cpp \
           mongo-cxx-driver/src/mongo/client/examples/insert_demo.cpp \
           mongo-cxx-driver/src/mongo/client/examples/rs.cpp \
           mongo-cxx-driver/src/mongo/client/examples/second.cpp \
           mongo-cxx-driver/src/mongo/client/examples/simple_client_demo.cpp \
           mongo-cxx-driver/src/mongo/client/examples/tail.cpp \
           mongo-cxx-driver/src/mongo/client/examples/tutorial.cpp \
           mongo-cxx-driver/src/mongo/client/examples/whereExample.cpp \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_conn_registry.cpp \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_dbclient_connection.cpp \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_dbclient_cursor.cpp \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_remote_db_server.cpp \
           mongo-cxx-driver/src/mongo/dbtests/mock/mock_replica_set.cpp \
           mongo-cxx-driver/src/mongo/util/concurrency/mutexdebugger.cpp \
           mongo-cxx-driver/src/mongo/util/concurrency/spin_lock.cpp \
           mongo-cxx-driver/src/mongo/util/concurrency/synchronization.cpp \
           mongo-cxx-driver/src/mongo/util/concurrency/thread_name.cpp \
           mongo-cxx-driver/src/mongo/util/net/httpclient.cpp \
           mongo-cxx-driver/src/mongo/util/net/listen.cpp \
           mongo-cxx-driver/src/mongo/util/net/message.cpp \
           mongo-cxx-driver/src/mongo/util/net/message_port.cpp \
           mongo-cxx-driver/src/mongo/util/net/sock.cpp \
           mongo-cxx-driver/src/mongo/util/net/sock_test.cpp \
           mongo-cxx-driver/src/mongo/util/net/socket_poll.cpp \
           mongo-cxx-driver/src/mongo/util/net/ssl_manager.cpp \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/codegear/gtest_all.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/codegear/gtest_link.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample1.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample10_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample1_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample2.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample2_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample3_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample4.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample4_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample5_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample6_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample7_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample8_unittest.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/samples/sample9_unittest.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-all.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-death-test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-filepath.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-port.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-printers.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-test-part.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest-typed-test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/src/gtest_main.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-death-test_ex_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-death-test_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-filepath_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-linked_ptr_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-listener_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-message_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-options_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-param-test2_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-param-test_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-port_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-printers_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-test-part_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-tuple_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-typed-test2_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-typed-test_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest-unittest-api_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_all_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_break_on_failure_unittest_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_catch_exceptions_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_color_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_env_var_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_environment_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_filter_unittest_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_help_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_list_tests_unittest_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_main_unittest.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_no_test_unittest.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_output_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_pred_impl_unittest.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_premature_exit_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_prod_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_repeat_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_shuffle_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_sole_header_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_stress_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_throw_on_failure_ex_test.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_throw_on_failure_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_uninitialized_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_unittest.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_xml_outfile1_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_xml_outfile2_test_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/gtest_xml_output_unittest_.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/test/production.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/fused-src/gtest/gtest-all.cc \
           mongo-cxx-driver/src/third_party/gtest-1.7.0/fused-src/gtest/gtest_main.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/xcode/Samples/FrameworkSample/widget.cc \
#           mongo-cxx-driver/src/third_party/gtest-1.7.0/xcode/Samples/FrameworkSample/widget_test.cc
